blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using urlfinder
    url: https://github.com/projectdiscovery/urlfinder/discussions/categories/q-a
    about: Ask a question or request support for using urlfinder

  - name: Share idea / feature to discuss for urlfinder
    url: https://github.com/projectdiscovery/urlfinder/discussions/categories/ideas
    about: Share idea / feature to discuss for urlfinder

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication